### PR TITLE
stub out API

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by j3k0** [comment]
Not much to say so far. All good!

Just wondering if those typedefs shouldn't be promoted to classes (except for the most basic ones). Typedef aren't exposed in Javascript and Actionscript.

If this file grows to big, feel free to split each feature-set in their own files too.

Looking forward for more

**Comment by ghost** [comment]
Seems like maybe this:

``` haskell
addGame :: LevelUpdateFunction -> LevelDecayFunction -> Array(PlayerArchive) -> Game -> Array(PlayerGameOutcome)
```

should be:

``` haskell
addGame :: LevelUpdateFunction -> LevelDecayFunction -> Array(PlayerArchive) -> Game -> Array(PlayerArchive)
```

Right? (Take an archive, a game, and return a new archive with the game added?)

And I'm afraid I don't understand this:

> Note: if the added game is already in the player archive: outcome will be an empty array.

By "outcome", do you mean the array returned by `addGame`?
If so, then I feel that the return value should be the unmodified array.

**Comment by j3k0** [comment]
Yes, by "outcome" of addGame I mean the return value.

The idea is that "addGame" gets access to the whole player archive, but just returns the new elements to insert into the archive. Imagine we link this to a SQL database, pseudo flow:

```
(SELECT * FROM archive) + game -> Alkindi.addGame -> (INSERT outcome INTO archive)
```

**Comment by ghost** [comment]
Alright, that makes sense.

**Pull request merged**
